no message

diff --git a/JenkinsfileTest b/JenkinsfileTest
--- a/JenkinsfileTest
+++ b/JenkinsfileTest
@@ -48,6 +48,29 @@ node {
         stage('Checkout pipeline') {
             git branch: 'feature-pipeline-bikeracks', url: 'https://github.com/mishel-uchuari/Replicate-LinkedOpenData-Datasets.git'
         }
+        
+        stage('Comprobar namespace') {
+		    try {
+		    timeout(time: 30, unit: 'SECONDS') {
+		      try {
+				  def ret = sh(script: 'java -jar blazegraph/blazegrapvalidator.jar ' +NameSpace+' '+entornoBlaze, returnStdout: true)
+		          if (ret.contains('No se ha generado RDF')) {
+		               sh 'exit 1'
+		          }
+		      }
+		      catch (err) {
+		        echo "For some reason, this catch is activated. Error: ${err.getMessage()}"
+		      }
+		      echo "This should not be executed, but it is!"
+		    }
+		  }
+		  catch (err) {
+		    echo "I expect that this catch will be activated. Error: ${err.getMessage()}"
+		  }
+        
+           
+        }
+        
         stage('Convert CSV to RDF') {
             def ret = sh(script: 'java -jar CSVToRDFBKLParkings/bklparkingsrdfcreator.jar ' + CSVBKLParkings + ' ' + NewCSVBKLParkings + ' ' + RmlConfigurationFile + ' ' + RDFBKLParkings+ ' ' + entorno+' '+NameSpace+' '+entornoBlaze, returnStdout: true)
             if (ret.contains('No se ha generado RDF')) {
